server:
  port: 80

spring:
  datasource:
    svc:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://test01:34706;DatabaseName=svc
      username: ******
      password: ******

    vf:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://test02:35488;DatabaseName=ExternalData
      username: ******
      password: ******

  mvc:
    favicon:
      enabled: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 150
        max-wait: -1
        max-idle: 8
        min-idle: 0
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:/root/img/vf/,file:/root/img/lee/



mybatis:
  type-aliases-package: com.iresearch.svc.bean
  mapper-locations: classpath:mapper/svc/*.xml,classpath:mapper/vf/*.xml

logging:
  config: classpath:log4j2.xml




